[package]
name = "timelog"
version = "0.1.0"
authors = ["Niklas Wallgren <niklasandersjonsson@gmail.com>"]
edition = "2024"

[dependencies]
docopt = "0.8"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
directories = "3.0"
log = "0.4"
env_logger = "0.10"
